In [8]:
import xarray as xr
import rasterio
from shapely.geometry import Polygon
import geopandas as gpd
import numpy as np
import os
import pandas as pd
from data_prep import h3_grid as h3
from ahp import Transformer

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Prueba

In [9]:
# wind_speed
path = 'COL_wind-speed_10m.tif'
ds_wind = rasterio.open(path)
crs = 'EPSG:9377'
resolution = 8

h3_module = h3(
    raster=ds_wind,
    resolution=8,
    crs=crs
)

path = 'codigo_tipos(in).csv'
df_data = pd.read_csv(path,sep=';',encoding='latin-1')
df_data = df_data.drop(['Criterio'], axis = 1)
df_data = df_data[~df_data['Subcriterio'].isna()]

In [10]:
archivos = pd.read_csv('codigo_tipos(in).csv',sep = ';')
archivos.head(1)

       Codigo Variable        Tipo Subcriterio  Criterio
0  AMB-001-AR    RUNAP  excluyente       Areas       NaN

In [ ]:
codigos_miro = [
    "AMB-003-A",
    "AMB-005-A",
    "AMB-006-A",
    "AMB-007-AT",
    "AMB-008-AT",
    "AMB-012-A",
    "AMB-017-A",
    "AMB-019-A",
    "AMB-020-A",
    "AMB-021-A",
    "AMB-028-A",
    # "AMB-030-AT",
    "AMB-031-A",
    "AMB-033-A",
    "AMB-034-A",
    "AMB-036-A",
    "AMB-038-A",
    # "TEC-016-A",
    "AMB-040-A"
]

In [12]:
archivos[archivos['Codigo'].isin(["AMB-031-A"])].reset_index(drop=True)

      Codigo    Variable     Tipo Subcriterio  Criterio
0  AMB-031-A  Sismicidad  binario    Amenazas       NaN

In [13]:
df = archivos[archivos['Codigo'].isin(["AMB-031-A"])].reset_index(drop=True)
map = h3_module.vars_ahp('vars_ambiental_ahp/',df)

procesando archivo AMB-031-A

In [14]:
map

,h3,geometry,AMB-031-A
0,88e74ab153fffff,"POLYGON ((5325672.764 2270751.835, 5326192.707...",0
1,88e74e391bfffff,"POLYGON ((5277632.122 2453118.543, 5278155.352...",0
2,88ef9e3307fffff,"POLYGON ((4714660.425 1703928.869, 4715184.234...",0
3,88e75c583bfffff,"POLYGON ((5400394.434 3191045.991, 5400910.973...",0
4,88f1693865fffff,"POLYGON ((3845240.623 1229251.959, 3845730.612...",0
...,...,...,...
1305221,88e758b033fffff,"POLYGON ((5428545.561 2785409.567, 5429063.776...",0
1305222,88eeb31139fffff,"POLYGON ((5181829.665 1182933.908, 5182326.141...",0
1305223,88ef9e12c7fffff,"POLYGON ((4690862.544 1837828.981, 4691391.747...",1
1305224,88f1691825fffff,"POLYGON ((3797756.295 1251269.183, 3798246.824...",0
1305225,88e76a571bfffff,"POLYGON ((5052953.546 2647235.922, 5053486.109...",0

In [12]:
map.to_file('preliminary-map')

/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 240 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.6999999760721821e+38 of field AMB-008-AT of feature 935 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 1138 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.6999999760721821e+38 of field AMB-008-AT of feature 1157 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 1256 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -8.4999998803609106e+37 of field AMB-008-AT of feature 1312 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 1389 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -8.4999998803609106e+37 of field AMB-008-AT of feature 1823 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 2073 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 2094 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 2148 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 2493 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -5.6666665869072741e+37 of field AMB-008-AT of feature 2536 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 2797 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -5.6666665869072741e+37 of field AMB-008-AT of feature 3021 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.6999999760721821e+38 of field AMB-008-AT of feature 3143 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 3470 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 3503 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -5.6666665869072741e+37 of field AMB-008-AT of feature 3769 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 4244 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 4850 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 5762 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 6098 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.6999999760721821e+38 of field AMB-008-AT of feature 6189 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 6321 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 6954 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -4.8571427887776636e+37 of field AMB-008-AT of feature 7041 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 7055 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -5.6666665869072741e+37 of field AMB-008-AT of feature 7915 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 8872 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -5.6666665869072741e+37 of field AMB-008-AT of feature 9439 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -8.4999998803609106e+37 of field AMB-008-AT of feature 9488 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 9555 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 10202 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.6999999760721821e+38 of field AMB-008-AT of feature 10301 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 10447 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -8.4999998803609106e+37 of field AMB-008-AT of feature 10512 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 10540 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 10910 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 11435 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -5.6666665869072741e+37 of field AMB-008-AT of feature 11684 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 12350 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -6.7999999042887281e+37 of field AMB-008-AT of feature 13203 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 13944 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -6.7999999042887281e+37 of field AMB-008-AT of feature 13950 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -6.7999999042887281e+37 of field AMB-008-AT of feature 14556 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -8.4999998803609106e+37 of field AMB-008-AT of feature 14858 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 15415 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -4.8571427887776636e+37 of field AMB-008-AT of feature 15675 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -8.4999998803609106e+37 of field AMB-008-AT of feature 15786 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -5.6666665869072741e+37 of field AMB-008-AT of feature 16082 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 17418 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 17842 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.6999999760721821e+38 of field AMB-008-AT of feature 18074 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 18848 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 18882 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -5.6666665869072741e+37 of field AMB-008-AT of feature 19015 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.6999999760721821e+38 of field AMB-008-AT of feature 19154 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 19734 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 19963 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 20406 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 20572 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 20613 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 21957 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.6999999760721821e+38 of field AMB-008-AT of feature 22084 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 22402 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 22616 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 22640 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 22794 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -4.8571427887776636e+37 of field AMB-008-AT of feature 23254 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -1.1333333173814548e+38 of field AMB-008-AT of feature 23289 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -3.3999999521443642e+38 of field AMB-008-AT of feature 23555 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(
/home/choclo/documents/ahpAmbiental/env/lib/python3.12/site-packages/pyogrio/raw.py:733: RuntimeWarning: Value -5.6666665869072741e+37 of field AMB-008-AT of feature 24420 not successfully written. Possibly due to too larger number with respect to field width
  ogr_write(